import {
  PawPrint,
  Gamepad2,
  Shield,
  Palette,
  Key,
  BookOpen,
  Briefcase,
  Calendar,
  Cloud,
  GitBranch,
  Bitcoin,
  DollarSign,
  CheckCircle,
  Code,
  BookMarked,
  FileText,
  Mail,
  Film,
  Leaf,
  MapPin,
  Landmark,
  Heart,
  Users,
  Trophy,
  Package,
  Car,
  Video,
  CloudRain,
  Brain,
  Music,
  Newspaper,
  Phone,
  Link,
  Camera,
  ShoppingBag,
  MessageCircle,
  Lock,
  FlaskConical,
  Type,
  Truck,
  type LucideIcon,
} from "lucide-react"

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  animals: PawPrint,
  anime: Gamepad2,
  "anti-malware": Shield,
  "art-and-design": Palette,
  "authentication-and-authorization": Key,
  blockchain: Bitcoin,
  books: BookOpen,
  business: Briefcase,
  calendar: Calendar,
  "cloud-storage-and-file-sharing": Cloud,
  "continuous-integration": GitBranch,
  cryptocurrency: Bitcoin,
  "currency-exchange": DollarSign,
  "data-validation": CheckCircle,
  development: Code,
  dictionaries: BookMarked,
  "documents-and-productivity": FileText,
  email: Mail,
  entertainment: Film,
  environment: Leaf,
  events: Calendar,
  finance: DollarSign,
  "food-and-drink": PawPrint,
  "games-and-comics": Gamepad2,
  geocoding: MapPin,
  government: Landmark,
  health: Heart,
  jobs: Briefcase,
  "machine-learning": Brain,
  music: Music,
  news: Newspaper,
  "open-data": Package,
  "open-source-projects": GitBranch,
  patent: FileText,
  personality: Users,
  phone: Phone,
  photography: Camera,
  programming: Code,
  "science-and-math": FlaskConical,
  security: Lock,
  shopping: ShoppingBag,
  social: MessageCircle,
  "sports-and-fitness": Trophy,
  "test-data": Package,
  "text-analysis": Type,
  tracking: Truck,
  transportation: Car,
  "url-shorteners": Link,
  vehicle: Car,
  video: Video,
  weather: CloudRain,
}

export function getCategoryIcon(categoryId: string): LucideIcon {
  return CATEGORY_ICONS[categoryId] || Package
}

export function CategoryIcon({
  categoryId,
  className = "size-4",
}: {
  categoryId: string
  className?: string
}) {
  const Icon = getCategoryIcon(categoryId)
  return <Icon className={className} aria-hidden="true" />
}
