export const DEFAULT_PER_PAGE = 20
export const MAX_PER_PAGE = 100

export const GRADE_ORDER = ["A", "B", "C", "D", "F"]

export const SORT_OPTIONS = [
  { value: "name", labelKey: "sortName" as const },
  { value: "quality", labelKey: "sortQuality" as const },
  { value: "category", labelKey: "sortCategory" as const },
  { value: "updated", labelKey: "sortUpdated" as const },
]

export const CATEGORY_ICONS: Record<string, string> = {
  animals: "🐾",
  anime: "🎌",
  analytics: "📊",
  "art-design": "🎨",
  auth: "🔐",
  blockchain: "⛓️",
  books: "📚",
  business: "💼",
  calendar: "📅",
  ci: "🔄",
  "cloud-storage": "☁️",
  collaboration: "🤝",
  cryptocurrency: "🪙",
  currency: "💱",
  "data-validation": "✅",
  development: "💻",
  dictionaries: "📖",
  documents: "📄",
  education: "🎓",
  email: "📧",
  entertainment: "🎬",
  environment: "🌱",
  events: "📅",
  finance: "💰",
  "food-drink": "🍔",
  "games-comics": "🎮",
  geocoding: "🗺️",
  government: "🏛️",
  health: "🏥",
  iot: "📡",
  jobs: "👔",
  "machine-learning": "🤖",
  media: "📺",
  music: "🎵",
  news: "📰",
  "open-data": "📊",
  "open-source": "🔧",
  other: "📦",
  patent: "📜",
  payment: "💳",
  personality: "🧠",
  phone: "📱",
  photography: "📷",
  programming: "🖥️",
  "science-math": "🔬",
  security: "🔒",
  shopping: "🛒",
  social: "👥",
  sports: "⚽",
  "sports-fitness": "⚽",
  telecom: "📞",
  "test-data": "🧪",
  "text-analysis": "📝",
  tracking: "📍",
  transportation: "🚗",
  "url-shorteners": "🔗",
  vehicle: "🚙",
  video: "🎥",
  weather: "🌤️",
}

export const SOURCE_LINKS: Record<string, string> = {
  "apis.guru": "https://apis.guru",
  "public-apis": "https://github.com/public-apis/public-apis",
  "marcelscruz/public-apis": "https://github.com/marcelscruz/public-apis",
  "n0shake/Public-APIs": "https://github.com/n0shake/Public-APIs",
  "public-api-lists/public-api-lists": "https://github.com/public-api-lists/public-api-lists",
  "keploy/public-apis-collection": "https://github.com/keploy/public-apis-collection",
}
